// SCREEN INFOS
#define VIDEO_ADDRESS 0xb8000
#define MAX_ROWS 25
#define MAX_COLS 80

// COLORS ON BLACK BACKGROUND
#define DEFAULT_COLOR 0x04
#define BLUE   0x09
#define GREEN  0x0A
#define CYAN   0x0B
#define RED    0x0C
#define PINK   0x0D
#define YELLOW 0x0E
#define WHITE  0x0F

// PORTS SCREEN
#define REG_SCREEN_CTRL 0x3D4
#define REG_SCREEN_DATA 0x3D5
